version: '3.8'
services:
  payment-service:
    build: .
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://payment-db:27017/paymentdb
    depends_on:
      - payment-db

  payment-db:
    image: mongo
    ports:
      - "27017:27017"