spring:
  data:
    mongodb:
      uri: mongodb://hotel-db:27017/hoteldb
  redis:
    host: redis
    port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: hotel-service
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer